import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MotionProvider from "@/components/providers/MotionProvider";
import "./globals.css";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const siteUrl = "https://squarefaceai.com";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "SquareFaceAI - Free AI Pixel Avatar Generator | Square Face Icon Maker",
    template: "%s | SquareFaceAI"
  },
  description: "Transform your photo into a unique square face pixel avatar with AI. Free online pixel avatar generator for Discord, Twitter, gaming profiles. Create cute pixel art avatars in 10 seconds - no signup required!",
  keywords: [
    "square face avatar generator",
    "pixel avatar maker",
    "ai avatar generator from photo",
    "discord avatar generator",
    "pixel art avatar",
    "square face icon generator",
    "photo to pixel avatar",
    "free avatar maker",
    "gaming avatar generator",
    "twitter profile picture generator",
    "cute pixel avatar",
    "minecraft style avatar",
  ],
  authors: [{ name: "SquareFaceAI", url: siteUrl }],
  creator: "SquareFaceAI",
  publisher: "SquareFaceAI",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: siteUrl,
  },
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
    ],
    apple: [
      { url: "/logo.svg", sizes: "180x180", type: "image/svg+xml" },
    ],
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteUrl,
    siteName: "SquareFaceAI",
    title: "SquareFaceAI - Free AI Pixel Avatar Generator",
    description: "Transform your photo into a unique square face pixel avatar with AI. Free, fast, no signup required!",
    // Images are auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "SquareFaceAI - Free AI Pixel Avatar Generator",
    description: "Transform your photo into a unique square face pixel avatar with AI. Free, fast, no signup!",
    creator: "@squarefaceai",
    // Images are auto-generated by twitter-image.tsx
  },
  // verification: {
  //   google: "YOUR_GOOGLE_VERIFICATION_CODE",  // Add after setting up Google Search Console
  // },
  category: "technology",
};

// JSON-LD Structured Data
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": `${siteUrl}/#website`,
      url: siteUrl,
      name: "SquareFaceAI",
      description: "AI-powered pixel avatar generator",
      publisher: {
        "@id": `${siteUrl}/#organization`
      },
      potentialAction: {
        "@type": "SearchAction",
        target: `${siteUrl}/?search={search_term_string}`,
        "query-input": "required name=search_term_string"
      }
    },
    {
      "@type": "Organization",
      "@id": `${siteUrl}/#organization`,
      name: "SquareFaceAI",
      url: siteUrl,
      logo: {
        "@type": "ImageObject",
        url: `${siteUrl}/logo.svg`,
        width: 180,
        height: 180
      },
      sameAs: [
        "https://twitter.com/squarefaceai",
        "https://github.com/squarefaceai",
        "https://discord.gg/squarefaceai"
      ]
    },
    {
      "@type": "SoftwareApplication",
      "@id": `${siteUrl}/#app`,
      name: "SquareFaceAI",
      applicationCategory: "MultimediaApplication",
      operatingSystem: "Web",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD"
      },
      aggregateRating: {
        "@type": "AggregateRating",
        ratingValue: "4.8",
        ratingCount: "1250",
        bestRating: "5",
        worstRating: "1"
      }
    },
    {
      "@type": "FAQPage",
      "@id": `${siteUrl}/#faq`,
      mainEntity: [
        {
          "@type": "Question",
          name: "How does SquareFaceAI work?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Simply upload your photo and our AI analyzes your facial features to create a unique pixel art avatar in about 10 seconds. No design skills required!"
          }
        },
        {
          "@type": "Question",
          name: "Is my photo stored on your servers?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "No, we prioritize your privacy. Your photos are processed in real-time and immediately deleted after generating your avatar. We never store your original images."
          }
        },
        {
          "@type": "Question",
          name: "What image formats do you support?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "We support JPG, PNG, and WEBP formats. For best results, use a clear, front-facing photo with good lighting."
          }
        },
        {
          "@type": "Question",
          name: "Can I use the avatar commercially?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Free tier avatars are for personal use only. Pro and Team plans include commercial use licenses for your generated avatars."
          }
        },
        {
          "@type": "Question",
          name: "What sizes are available?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Free users get 256px avatars. Pro users can export up to 1024px for crisp, high-quality avatars perfect for any platform."
          }
        }
      ]
    },
    {
      "@type": "BreadcrumbList",
      "@id": `${siteUrl}/#breadcrumb`,
      itemListElement: [
        {
          "@type": "ListItem",
          position: 1,
          name: "Home",
          item: siteUrl
        }
      ]
    }
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className={`${inter.variable} antialiased`}>
        <MotionProvider>
          {children}
        </MotionProvider>
      </body>
    </html>
  );
}
