'use client';

import { useState } from 'react';
import { ChevronDown } from 'lucide-react';

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      question: 'How does SquareFaceAI work?',
      answer: 'SquareFaceAI uses advanced AI technology (Google Gemini Vision) to analyze your facial features from your photo and transform them into a unique pixel art avatar. The entire process takes about 10 seconds!',
    },
    {
      question: 'Is my photo stored on your servers?',
      answer: 'No! We value your privacy. Your photos are processed in real-time and are never stored on our servers. Once your avatar is generated, the original photo is immediately deleted.',
    },
    {
      question: 'What image formats do you support?',
      answer: 'We support all common image formats including JPG, PNG, and WEBP. Maximum file size is 5MB.',
    },
    {
      question: 'Can I use the avatar commercially?',
      answer: 'Yes! All avatars generated by SquareFaceAI are yours to use however you like - personal or commercial use, no attribution required.',
    },
    {
      question: 'What sizes are available?',
      answer: 'Free users get 256x256px avatars. Pro users can export up to 1024x1024px for crisp quality on any platform.',
    },
    {
      question: 'How is this different from other avatar generators?',
      answer: 'Unlike traditional generators that require manual assembly (5-10 minutes), SquareFaceAI uses AI to analyze YOUR actual photo and creates a personalized avatar in just 10 seconds. Every avatar is unique to your face!',
    },
  ];

  return (
    <section id="faq" className="py-20 bg-zinc-900/30">
      <div className="container mx-auto px-6">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold mb-4">
            Frequently Asked <span className="gradient-text">Questions</span>
          </h2>
          <p className="text-zinc-400 text-lg max-w-2xl mx-auto">
            Got questions? We&apos;ve got answers. Can&apos;t find what you&apos;re looking for? Contact us!
          </p>
        </div>

        <div className="max-w-3xl mx-auto space-y-4">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="glass rounded-xl overflow-hidden transition-all duration-300 hover:glow-purple"
            >
              <button
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                className="w-full px-6 py-5 flex items-center justify-between text-left hover:bg-zinc-800/50 transition-colors"
              >
                <span className="font-semibold text-lg pr-4">{faq.question}</span>
                <ChevronDown
                  className={`w-5 h-5 flex-shrink-0 transition-transform duration-300 ${
                    openIndex === index ? 'rotate-180' : ''
                  }`}
                />
              </button>
              <div
                className={`overflow-hidden transition-all duration-300 ${
                  openIndex === index ? 'max-h-96' : 'max-h-0'
                }`}
              >
                <div className="px-6 pb-5 text-zinc-400 leading-relaxed">
                  {faq.answer}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
